#!/usr/bin/env python3
"""Precompute approximate routes between the approximate body-found pins (Ekurhuleni cases only) for the
HYPOTHETICAL scenario views. Uses the public OSRM instances run by FOSSGIS (routing.openstreetmap.de:
routed-car = car profile, routed-foot = foot profile), based on OpenStreetMap data. Durations are the
router's free-flow estimates (no traffic, no waiting). Pins are suburb/road level, so all distances and
times are approximate. Output: data/routes.json and js/routes.js (window.ROUTE_DATA)."""
import json, os, sys, time, math, urllib.request
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
cases = json.load(open(os.path.join(ROOT, "data", "cases.json")))["cases"]
sites = [c for c in cases if c["id"] != "soweto"]
UA = {"User-Agent": "ekurhuleni-case-map-build/1.0 (static research site; low volume)"}
BASE = {"driving": "https://routing.openstreetmap.de/routed-car", "foot": "https://routing.openstreetmap.de/routed-foot"}
PROF = {"driving": "driving", "foot": "foot"}
def get(url):
    for i in range(4):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=40) as r:
                return json.load(r)
        except Exception as e:
            print("retry", i, e); time.sleep(3 + i * 3)
    raise SystemExit("routing failed: " + url)
def hav(a, b):
    R = 6371.0; la1, lo1, la2, lo2 = map(math.radians, (a[0], a[1], b[0], b[1]))
    h = math.sin((la2 - la1) / 2) ** 2 + math.cos(la1) * math.cos(la2) * math.sin((lo2 - lo1) / 2) ** 2
    return 2 * R * math.asin(math.sqrt(h))
coords = ";".join(f'{c["found"]["lng"]},{c["found"]["lat"]}' for c in sites)
ids = [c["id"] for c in sites]
matrix = {}
for p in ("driving", "foot"):
    d = get(f'{BASE[p]}/table/v1/{PROF[p]}/{coords}?annotations=duration,distance')
    assert d.get("code") == "Ok", d
    matrix[p] = {"durationMin": [[round(x / 60, 1) if x is not None else None for x in row] for row in d["durations"]],
                 "distanceKm": [[round(x / 1000, 1) if x is not None else None for x in row] for row in d["distances"]]}
    time.sleep(1.2)
straight = [[round(hav((a["found"]["lat"], a["found"]["lng"]), (b["found"]["lat"], b["found"]["lng"])), 1) for b in sites] for a in sites]
geoms = {}
n = len(sites)
for i in range(n):
    for j in range(i + 1, n):
        a, b = sites[i], sites[j]
        for p in ("driving", "foot"):
            d = get(f'{BASE[p]}/route/v1/{PROF[p]}/{a["found"]["lng"]},{a["found"]["lat"]};{b["found"]["lng"]},{b["found"]["lat"]}?overview=simplified&geometries=geojson')
            g = d["routes"][0]["geometry"]["coordinates"]
            geoms[f"{ids[i]}|{ids[j]}|{p}"] = [[round(y, 4), round(x, 4)] for x, y in g]
            time.sleep(1.05)
    print("row", i, "done")
out = dict(meta=dict(
    generated=time.strftime("%Y-%m-%d"),
    method="Routes and times computed with OSRM (FOSSGIS public servers routing.openstreetmap.de, car and foot profiles, OpenStreetMap data) between the approximate map pins. Straight-line distances are great-circle distances between the same pins.",
    caveats=["Pins are suburb/road level, so every distance and time is approximate (typically ±1-3 km).",
             "Drive times are free-flow router estimates with no traffic; walking times assume about 5 km/h on walkable ways.",
             "These numbers describe geography only. They are not evidence that any cases are linked."],
    source=dict(title="OSRM routing on OpenStreetMap data (routing.openstreetmap.de, FOSSGIS)", url="https://routing.openstreetmap.de/", outlet="FOSSGIS e.V. / OpenStreetMap contributors (ODbL)", date="computed " + time.strftime("%Y-%m-%d"))),
  ids=ids, straightKm=straight, matrix=matrix, geoms=geoms)
json.dump(out, open(os.path.join(ROOT, "data", "routes.json"), "w"))
open(os.path.join(ROOT, "js", "routes.js"), "w").write("// Generated by tools/build_routes.py (approximate routes between approximate pins; see meta).\nwindow.ROUTE_DATA = " + json.dumps(out) + ";\n")
print("sites", n, "geoms", len(geoms))
